apiVersion: v1
kind: Pod
metadata:
  name: union-example-pod
spec:
  containers:
  - name: app
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: vol
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: union-example-pvc
