kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: union-csi-attacher-binding
subjects:
  - kind: ServiceAccount
    name: union-service-account
    namespace: union
roleRef:
  kind: ClusterRole
  name: union-csi-attacher-role
  apiGroup: rbac.authorization.k8s.io

