kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: union-binding
subjects:
  - kind: ServiceAccount
    name: union-service-account
    namespace: union
roleRef:
  kind: ClusterRole
  name: union-role
  apiGroup: rbac.authorization.k8s.io

