kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: union-csi-driver-node
  namespace: union
  labels:
    app.kubernetes.io/name: union-csi-driver-node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: union-csi-driver-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: union-csi-driver-node
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccount: union-service-account
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        runAsNonRoot: false
      containers:
      - name: union-csi-driver
        image: docker.io/on2e/union-csi-driver:demo
        imagePullPolicy: "Always"
        args:
        - --mode=node
        - --endpoint=$(CSI_ENDPOINT)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: socket-dir
          mountPath: /csi/
        - name: kubelet-dir
          mountPath: /var/lib/kubelet/
          mountPropagation: Bidirectional
        - name: driver-dir
          mountPath: /var/lib/union-csi-driver.union.io/
          mountPropagation: Bidirectional
        securityContext:
          privileged: true
      - name: csi-node-driver-registrar
        image: docker.io/on2e/csi-node-driver-registrar:v2.8.0
        imagePullPolicy: "IfNotPresent"
        args:
        - --csi-address=$(CSI_ENDPOINT)
        - --kubelet-registration-path=$(KUBELET_REGISTRATION_PATH)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBELET_REGISTRATION_PATH
          value: /var/lib/kubelet/plugins/union-csi-driver.union.io/csi.sock
        volumeMounts:
        - name: registration-dir
          mountPath: /registration/
        - name: socket-dir
          mountPath: /csi/
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: kubelet-dir
        hostPath:
          path: /var/lib/kubelet/
          type: Directory
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/union-csi-driver.union.io/
          type: DirectoryOrCreate
      - name: driver-dir
        hostPath:
          path: /var/lib/union-csi-driver.union.io/
          type: DirectoryOrCreate
