kind: Deployment
apiVersion: apps/v1
metadata:
  name: union-csi-driver-controller
  namespace: union
  labels:
    app.kubernetes.io/name: union-csi-driver-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: union-csi-driver-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: union-csi-driver-controller
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccount: union-service-account
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: union-csi-driver
        image: docker.io/on2e/union-csi-driver:demo
        imagePullPolicy: "Always"
        args:
        - --mode=controller
        - --endpoint=$(CSI_ENDPOINT)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: socket-dir
          mountPath: /csi/
        securityContext:
          allowPrivilegeEscalation: false
      - name: csi-provisioner
        image: docker.io/on2e/csi-provisioner:v3.5.0
        imagePullPolicy: "IfNotPresent"
        args:
        - --csi-address=$(CSI_ENDPOINT)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi/
        securityContext:
          allowPrivilegeEscalation: false
      - name: csi-attacher
        image: docker.io/on2e/csi-attacher:v4.3.0
        imagePullPolicy: "IfNotPresent"
        args:
        - --csi-address=$(CSI_ENDPOINT)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi/
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: socket-dir
        emptyDir:
