apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../pkg/k8s/config/crd/
- namespace.yaml
- serviceaccount.yaml
- clusterrole-union.yaml
- clusterrole-provisioner.yaml
- clusterrole-attacher.yaml
- clusterrolebinding-union.yaml
- clusterrolebinding-provisioner.yaml
- clusterrolebinding-attacher.yaml
- daemonset-driver-node.yaml
- deployment-driver-controller.yaml
